### ISSUE TITLE
Main item list does not render in Firefox Nightly

### ISSUE THREAD

**Issue by wanderview** [googlearchive/todomvc#8] opened 2013-06-18 14:37 UTC
The app renders correctly in Firefox Beta (22), but the main item list does not appear in Firefox Nightly (24a 6/18/2013).

The one difference I see in the console is that the polymer.min.js file produces a NotSupportedError on Nightly.

Looking at polymer.min.js I see a couple uses of `eval()`.  Perhaps the failure is due to [CSP](https://hacks.mozilla.org/2013/05/content-security-policy-1-0-lands-in-firefox-aurora/) support in Firefox 23+.

**Comment by arv** [comment] 2013-06-18 15:22
Duplicate of https://github.com/Polymer/ShadowDOM/issues/159

**Closed as completed** 2013-06-18 15:22 UTC
Labels: duplicate
